# Generated by Django 3.1.1 on 2020-10-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_remove_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Display_Pic',
            field=models.ImageField(default='default.svg', upload_to='profile_images'),
        ),
    ]
